# SITE CONFIGURATION
baseurl: "/webtest2"
url: "https://cshuler-sitetest.github.io"

# THEME-SPECIFIC CONFIGURATION
title: Shuler Hydrologic                                    # site's title
description: "Groundwater, surface water, and coastal hydrology specializing in groundwater modeling, GIS, data analysis, water quality, field studies, and data science"      # used by search engines
avatar: assets/sh/logo.png                         # Empty for no avatar in navbar
favicon: assets/sh/logo.png                         # Icon displayed in the tab

# Header and footer text
header_text: Shuler Hydrologic  # Change Blog header text
header_feature_image: assets/sh/water.jpg
footer_text: >
  Created by Shuler Hydrologic LLC, Powered by <a href="https://jekyllrb.com/">Jekyll</a> from <a href="https://github.com/sylhare/Type-on-Strap">sylhare</a>

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
katex: true                                             # Enable if using math markup
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
disqus_shortname:                                       # Your discus shortname for comments
layout_variables:                                       # Open the "_sass > base" folder, and open "_variables.scss"
footer_icons:                                           # In _data/social.yml
share_buttons:                                          # In _data/social.yml
authors:                                                # In _data/authors.yml
language:                                               # In _data/language.yml

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
